# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Solvely' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Solvely
  pod "CameraEngine"
  pod 'NVActivityIndicatorView'
  pod 'TOCropViewController'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'havenondemand'
  pod 'RxAlamofire'
  
end
