# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Solvely' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Solvely
  pod "FastttCamera/Filters"
  pod 'TOCropViewController'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'RxAlamofire'
  pod 'Gloss', '~> 0.7'
  pod 'BubbleTransition', '~> 1.0.0'
  pod 'MBProgressHUD'
  pod "NMPopUpViewSwift"
  pod 'CNPPopupController'
end
